#!/bin/sh
set -e

export CLOUDIAC_WORKSPACE="${CLOUDIAC_WORKSPACE:-/cloudiac/workspace}"
export CLOUDIAC_WORKDIR="${CLOUDIAC_WORKDIR}"
export CLOUDIAC_TERRAFORM_PY="${CLOUDIAC_TERRAFORM_PY:-/cloudiac/assets/terraform.py}"
export CLOUDIAC_ANSIBLE_USER="${CLOUDIAC_ANSIBLE_USER:-root}"

COMMAND="ansible-playbook --user $CLOUDIAC_ANSIBLE_USER --inventory $CLOUDIAC_TERRAFORM_PY"

test -e "$CLOUDIAC_WORKSPACE/_cloudiac_play_vars.yml" && COMMAND="$COMMAND --extra @$CLOUDIAC_WORKSPACE/_cloudiac_play_vars.yml"
test -e "$CLOUDIAC_WORKSPACE/ssh_key" && COMMAND="$COMMAND --private-key $CLOUDIAC_WORKSPACE/ssh_key"

if [[ -z "$ANSIBLE_TF_DIR" ]]; then
  true
  if test -e "${CLOUDIAC_WORKSPACE}/code/${CLOUDIAC_WORKDIR}"; then 
    ANSIBLE_TF_DIR="${CLOUDIAC_WORKSPACE}/code/${CLOUDIAC_WORKDIR}"
  elif test -e "${CLOUDIAC_WORKSPACE}"; then 
    ANSIBLE_TF_DIR="${CLOUDIAC_WORKSPACE}"
  else 
    ANSIBLE_TF_DIR="."
  fi
fi

export ANSIBLE_TF_DIR
export ANSIBLE_NOCOWS="${ANSIBLE_NOCOWS:-1}"
export ANSIBLE_HOST_KEY_CHECKING="${ANSIBLE_HOST_KEY_CHECKING:-False}"
$COMMAND $@
