// Copyright (c) 2015-2022 CloudJ Technology Co., Ltd.

// Code generated by code-gen/desenitize DO NOT EDIT

package desensitize

import (
	"cloudiac/portal/models"
)

type ScanTask struct {
	models.ScanTask
}

//func (v ScanTask) MarshalJSON() ([]byte, error) {
//	return json.Marshal(v.ScanTask.Desensitize())
//}
//
//func NewScanTask(v models.ScanTask) ScanTask {
//	rv := ScanTask{v.Desensitize()}
//	return rv
//}
//
//func NewScanTaskPtr(v *models.ScanTask) *ScanTask {
//	rv := ScanTask{v.Desensitize()}
//	return &rv
//}

//func NewScanTaskSlice(vs []models.ScanTask) []ScanTask {
//	rvs := make([]ScanTask, len(vs))
//	for i := 0; i < len(vs); i++ {
//		rvs[i] = NewScanTask(vs[i])
//	}
//	return rvs
//}
//
//func NewScanTaskSlicePtr(vs []*models.ScanTask) []*ScanTask {
//	rvs := make([]*ScanTask, len(vs))
//	for i := 0; i < len(vs); i++ {
//		v := NewScanTask(*vs[i])
//		rvs[i] = &v
//	}
//	return rvs
//}
