// Copyright (c) 2015-2023 CloudJ Technology Co., Ltd.

// Code generated by code-gen/desenitize DO NOT EDIT

package desensitize

import (
	// "encoding/json"
	"cloudiac/portal/models"
)

type VariableGroup struct {
	models.VariableGroup
}


// 不定义 MarshalJSON() 方法，因为一旦定义了该结构体就无法组合使用了，
// 会覆盖 MarshalJSON() 方法以导致组合的其他字段不输出。 比如定义结构体:
// type VariableGroupWithExt struct {
// 		models.VariableGroup
//		Ext	string
// }
// 当我们调用 json.Marshal(VariableGroupWithExt{}) 时 Ext 字段不会输出，
// 因为直接调用了 models.VariableGroup.MarshalJSON() 方法。
// func (v VariableGroup) MarshalJSON() ([]byte, error) {
// 	return json.Marshal(v.VariableGroup.Desensitize())
// }
func (v VariableGroup) Desensitize() VariableGroup {
	return VariableGroup{v.VariableGroup.Desensitize()}
}

func NewVariableGroup(v models.VariableGroup) VariableGroup {
	rv := VariableGroup{v.Desensitize()}
	return rv
}

func NewVariableGroupPtr(v *models.VariableGroup) *VariableGroup {
	rv := VariableGroup{v.Desensitize()}
	return &rv
}

func NewVariableGroupSlice(vs []models.VariableGroup) []VariableGroup {
	rvs := make([]VariableGroup, len(vs))
	for i := 0; i < len(vs); i++ {
		rvs[i] = NewVariableGroup(vs[i])
	}
	return rvs
}

func NewVariableGroupSlicePtr(vs []*models.VariableGroup) []*VariableGroup {
	rvs := make([]*VariableGroup, len(vs))
	for i := 0; i < len(vs); i++ {
		v := NewVariableGroup(*vs[i])
		rvs[i] = &v
	}
	return rvs
}
