// Copyright (c) 2015-2022 CloudJ Technology Co., Ltd.

// Code generated by code-gen/desenitize DO NOT EDIT

package desensitize

import (
	"encoding/json"
	"cloudiac/portal/models"
)

type Variable struct {
	models.Variable
}

func (v Variable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Variable.Desensitize())
}

func NewVariable(v models.Variable) Variable {
	rv := Variable{v.Desensitize()}
	return rv
}

func NewVariablePtr(v *models.Variable) *Variable {
	rv := Variable{v.Desensitize()}
	return &rv
}

func NewVariableSlice(vs []models.Variable) []Variable {
	rvs := make([]Variable, len(vs))
	for i := 0; i < len(vs); i++ {
		rvs[i] = NewVariable(vs[i])
	}
	return rvs
}

func NewVariableSlicePtr(vs []*models.Variable) []*Variable {
	rvs := make([]*Variable, len(vs))
	for i := 0; i < len(vs); i++ {
		v := NewVariable(*vs[i])
		rvs[i] = &v
	}
	return rvs
}
