// Copyright (c) 2015-2022 CloudJ Technology Co., Ltd.

// Code generated by code-gen/desenitize DO NOT EDIT

package desensitize

import (
	"encoding/json"
	"cloudiac/portal/models"
)

type VariableGroup struct {
	models.VariableGroup
}

func (v VariableGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.VariableGroup.Desensitize())
}

func NewVariableGroup(v models.VariableGroup) VariableGroup {
	rv := VariableGroup{v.Desensitize()}
	return rv
}

func NewVariableGroupPtr(v *models.VariableGroup) *VariableGroup {
	rv := VariableGroup{v.Desensitize()}
	return &rv
}

func NewVariableGroupSlice(vs []models.VariableGroup) []VariableGroup {
	rvs := make([]VariableGroup, len(vs))
	for i := 0; i < len(vs); i++ {
		rvs[i] = NewVariableGroup(vs[i])
	}
	return rvs
}

func NewVariableGroupSlicePtr(vs []*models.VariableGroup) []*VariableGroup {
	rvs := make([]*VariableGroup, len(vs))
	for i := 0; i < len(vs); i++ {
		v := NewVariableGroup(*vs[i])
		rvs[i] = &v
	}
	return rvs
}
