// Copyright (c) 2015-2022 CloudJ Technology Co., Ltd.

// Code generated by code-gen/desenitize DO NOT EDIT

package desensitize

import (
	"encoding/json"
	"cloudiac/portal/models"
)

type Vcs struct {
	models.Vcs
}

func (v Vcs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Vcs.Desensitize())
}

func NewVcs(v models.Vcs) Vcs {
	rv := Vcs{v.Desensitize()}
	return rv
}

func NewVcsPtr(v *models.Vcs) *Vcs {
	rv := Vcs{v.Desensitize()}
	return &rv
}

func NewVcsSlice(vs []models.Vcs) []Vcs {
	rvs := make([]Vcs, len(vs))
	for i := 0; i < len(vs); i++ {
		rvs[i] = NewVcs(vs[i])
	}
	return rvs
}

func NewVcsSlicePtr(vs []*models.Vcs) []*Vcs {
	rvs := make([]*Vcs, len(vs))
	for i := 0; i < len(vs); i++ {
		v := NewVcs(*vs[i])
		rvs[i] = &v
	}
	return rvs
}
