FROM cloudiac/base-ct-worker:v0.2.2

COPY assets/terraform.py /cloudiac/assets/terraform.py
COPY assets/terraformrc-* /cloudiac/assets/
COPY assets/cloudiac-playbook /usr/local/bin/cloudiac-playbook
COPY build/iac-tool /usr/yunji/cloudiac/iac-tool
