ARG REPOS
FROM ${REPOS} as repos

FROM arm64v8/alpine
RUN apk add --no-cache netcat-openbsd curl
ENV TZ="Asia/Shanghai"

ARG WORKDIR=/usr/yunji/cloudiac/
WORKDIR ${WORKDIR}
COPY --from=repos /usr/yunji/cloudiac/repos ${WORKDIR}/repos
