// Copyright (c) 2015-2022 CloudJ Technology Co., Ltd.
// THIS FILE GENERATED BY 'gen-lang' DO NOT EDIT

package e

var langs = []string{"zh-cn", "en-us"}

var errorMsgs = map[int]map[string]string{
	InternalError: {
		"en-us": "internal error",
		"zh-cn": "未知错误",
	},
	ObjectAlreadyExists: {
		"en-us": "object already exists",
		"zh-cn": "对象已存在",
	},
	ObjectNotExists: {
		"en-us": "object not exists",
		"zh-cn": "对象不存在",
	},
	ObjectNotExistsOrNoPerm: {
		"en-us": "object not exists or no permisson to access object",
		"zh-cn": "对象不存在或者无权限",
	},
	ObjectDisabled: {
		"en-us": "object disabled",
		"zh-cn": "对象已禁用",
	},
	JSONParseError: {
		"en-us": "invalid json",
		"zh-cn": "JSON 数据解析出错",
	},
	URLParseError: {
		"en-us": "invalid url",
		"zh-cn": "URL解析出错",
	},
	NotImplement: {
		"en-us": "not implemented",
		"zh-cn": "暂未实现",
	},
	DBError: {
		"en-us": "database error",
		"zh-cn": "数据库错误",
	},
	DBAttrValidateErr: {
		"en-us": "database attribute invalidate",
		"zh-cn": "字段验证错误",
	},
	BadOrgId: {
		"en-us": "invalid organization id",
		"zh-cn": "组织 ID 错误",
	},
	BadProjectId: {
		"en-us": "invalid project id",
		"zh-cn": "项目 ID 错误",
	},
	BadTemplateId: {
		"en-us": "invalid templated id",
		"zh-cn": "模板 ID 错误",
	},
	BadEnvId: {
		"en-us": "invalid environment id",
		"zh-cn": "环境 ID 错误",
	},
	BadParam: {
		"en-us": "invalid or missing parameter",
		"zh-cn": "无效参数",
	},
	TemplateNameRepeat: {
		"en-us": "duplicated template name",
		"zh-cn": "云模版名称重复",
	},
	TemplateWorkdirError: {
		"en-us": "invalid template working directory",
		"zh-cn": "工作目录校验失败",
	},
	BadRequest: {
		"en-us": "bad request",
		"zh-cn": "无效请求",
	},
	InvalidPipeline: {
		"en-us": "invalid pipeline definition",
		"zh-cn": "pipeline 格式错误",
	},
	InvalidPipelineVersion: {
		"en-us": "invalid pipeline version",
		"zh-cn": "不支持的 pipeline 版本",
	},
	InvalidExportVersion: {
		"en-us": "data format version not supported",
		"zh-cn": "不支持的导出数据版本",
	},
	DataTooLong: {
		"en-us": "request data too large",
		"zh-cn": "内容过长",
	},
	NameTooLong: {
		"en-us": "name too long",
		"zh-cn": "名称过长",
	},
	RemarkTooLong: {
		"en-us": "remark too long",
		"zh-cn": "备注过长",
	},
	TagTooLong: {
		"en-us": "tag too long",
		"zh-cn": "标签过长",
	},
	TagTooMuch: {
		"en-us": "number of tags exceeds system limit",
		"zh-cn": "标签过多",
	},
	IOError: {
		"en-us": "unexpected io error",
		"zh-cn": "io 错误",
	},
	TooManyRetries: {
		"en-us": "too many retries",
		"zh-cn": "达到最大重试次数",
	},
	EncryptError: {
		"en-us": "data encryption error",
		"zh-cn": "数据加密错误",
	},
	DecryptError: {
		"en-us": "data dencryption error",
		"zh-cn": "数据解密错误",
	},
	MailServerError: {
		"en-us": "failed to send email",
		"zh-cn": "邮件服务错误",
	},
	InvalidAccessKeyId: {
		"en-us": "invalid access key id",
		"zh-cn": "AccessKeyId错误",
	},
	InvalidAccessKeySecret: {
		"en-us": "invalid access key secret",
		"zh-cn": "AccessKeySecret错误",
	},
	ForbiddenAccessKey: {
		"en-us": "access denied",
		"zh-cn": "AccessKey权限不足",
	},
	InvalidToken: {
		"en-us": "invalid token",
		"zh-cn": "凭证无效",
	},
	InvalidTokenScope: {
		"en-us": "invalid token scope",
		"zh-cn": "凭证 scope 不匹配",
	},
	InvalidOrgId: {
		"en-us": "invalid organization id",
		"zh-cn": "无效的组织",
	},
	TokenExpired: {
		"en-us": "token expired",
		"zh-cn": "凭证已过期",
	},
	ColValidateError: {
		"en-us": "database column invalid",
		"zh-cn": "字段校验错误",
	},
	InvalidPassword: {
		"en-us": "invalid account or password",
		"zh-cn": "无效的邮箱或密码",
	},
	InvalidColumn: {
		"en-us": "invalid column",
		"zh-cn": "无效的字段名",
	},
	InvalidOperation: {
		"en-us": "invalid operation",
		"zh-cn": "无效操作",
	},
	UserAlreadyExists: {
		"en-us": "user already exists",
		"zh-cn": "用户已存在",
	},
	UserNotExists: {
		"en-us": "user does not exists",
		"zh-cn": "用户不存在",
	},
	UserEmailDuplicate: {
		"en-us": "email address already exists",
		"zh-cn": "用户邮箱已存在",
	},
	UserEmailDuplicateInactive: {
		"en-us": "email address inactive",
		"zh-cn": "无效的用户邮箱",
	},
	UserInvalidStatus: {
		"en-us": "invalid user status",
		"zh-cn": "无效的用户状态",
	},
	UserInactive: {
		"en-us": "user is inactive",
		"zh-cn": "用户未激活",
	},
	UserDisabled: {
		"en-us": "user is disabled",
		"zh-cn": "用户已禁用",
	},
	InvalidPasswordFormat: {
		"en-us": "password does not meet complexity requirement",
		"zh-cn": "密码格式错误",
	},
	UserActivated: {
		"en-us": "user already activated",
		"zh-cn": "账号已激活",
	},
	InvalidRoleName: {
		"en-us": "invalid role name",
		"zh-cn": "无效角色名",
	},
	RoleNameDuplicate: {
		"en-us": "role name already exists",
		"zh-cn": "角色名重复",
	},
	PermissionDeny: {
		"en-us": "access denied",
		"zh-cn": "无权限",
	},
	PermDenyApproval: {
		"en-us": "access denied",
		"zh-cn": "无审批权限",
	},
	ValidateError: {
		"en-us": "login validation fail",
		"zh-cn": "验证失败",
	},
	OrganizationAlreadyExists: {
		"en-us": "organization already exists",
		"zh-cn": "组织已存在",
	},
	OrganizationNotExists: {
		"en-us": "organization not exists",
		"zh-cn": "组织不存在",
	},
	OrganizationDisabled: {
		"en-us": "organization disabled",
		"zh-cn": "组织被禁用",
	},
	OrganizationInvalidStatus: {
		"en-us": "organization invalid status",
		"zh-cn": "无效的组织状态",
	},
	InvalidOrganizationId: {
		"en-us": "invalid organization id",
		"zh-cn": "无效的组织ID",
	},
	NameDuplicate: {
		"en-us": "user already exists",
		"zh-cn": "名称重复",
	},
	TaskStepNotExists: {
		"en-us": "task step does not exists",
		"zh-cn": "步骤不存在",
	},
	InvalidProjectId: {
		"en-us": "invalid project id",
		"zh-cn": "无效的项目id",
	},
	TaskNotHaveStep: {
		"en-us": "task have no steps",
		"zh-cn": "任务无步骤",
	},
	TemplateAlreadyExists: {
		"en-us": "template already exists",
		"zh-cn": "模板名称重复",
	},
	HCLParseError: {
		"en-us": "hcl parse error",
		"zh-cn": "模板语法解析错误",
	},
	VariableAlreadyExists: {
		"en-us": "variable already exists",
		"zh-cn": "变量已存在",
	},
	VariableAliasDuplicate: {
		"en-us": "variable alias name already exists",
		"zh-cn": "变量别名重复",
	},
	VariableScopeConflict: {
		"en-us": "variable scope conflict",
		"zh-cn": "变量作用域冲突",
	},
	InvalidVarName: {
		"en-us": "invalid variable name",
		"zh-cn": "无效变量名",
	},
	EmptyVarName: {
		"en-us": "variable name is empty",
		"zh-cn": "变量名不可为空",
	},
	EmptyVarValue: {
		"en-us": "variable value is empty",
		"zh-cn": "变量值不可为空",
	},
	ProjectUserAlreadyExists: {
		"en-us": "project user already exists",
		"zh-cn": "项目用户已经存在",
	},
	ProjectUserAliasDuplicate: {
		"en-us": "project name already exists",
		"zh-cn": "项目别名重复",
	},
	TokenAlreadyExists: {
		"en-us": "token already exists",
		"zh-cn": "Token已经存在",
	},
	TokenNotExists: {
		"en-us": "token does not exists",
		"zh-cn": "Token不存在",
	},
	TokenAliasDuplicate: {
		"en-us": "token alias already exists",
		"zh-cn": "Token别名重复",
	},
	TemplateNotExists: {
		"en-us": "template not exists",
		"zh-cn": "模板不存在",
	},
	TemplateDisabled: {
		"en-us": "template disabled",
		"zh-cn": "模板不可用",
	},
	TemplateActiveEnvExists: {
		"en-us": "can not delete template which have active environment",
		"zh-cn": "模板存在活跃环境",
	},
	ConsulConnError: {
		"en-us": "connect to consul error",
		"zh-cn": "consul链接失败",
	},
	EnvAlreadyExists: {
		"en-us": "environment already exists",
		"zh-cn": "环境已经存在",
	},
	EnvNotExists: {
		"en-us": "environment not exists",
		"zh-cn": "环境不存在",
	},
	EnvAliasDuplicate: {
		"en-us": "environment alias already exists",
		"zh-cn": "环境别名重复",
	},
	EnvArchived: {
		"en-us": "environment had been archived",
		"zh-cn": "环境已归档，不允许操作",
	},
	EnvDeploying: {
		"en-us": "deployment in progress",
		"zh-cn": "环境正在部署中，请不要重复发起",
	},
	EnvCheckAutoApproval: {
		"en-us": "auto approval is required",
		"zh-cn": "配置自动纠漂移、推送到分支时重新部署时，必须配置自动审批",
	},
	TaskAlreadyExists: {
		"en-us": "task already exists",
		"zh-cn": "任务已经存在",
	},
	TaskNotExists: {
		"en-us": "task does not exists",
		"zh-cn": "任务不存在",
	},
	VcsError: {
		"en-us": "unknown VCS error",
		"zh-cn": "VCS仓库错误",
	},
	VcsAddressError: {
		"en-us": "invalid VCS address",
		"zh-cn": "VCS地址错误",
	},
	VcsInvalidToken: {
		"en-us": "VCS token invalid",
		"zh-cn": "VCS令牌无效",
	},
	VcsConnectError: {
		"en-us": "connect to VCS failed",
		"zh-cn": "VCS服务连接失败",
	},
	VcsConnectTimeOut: {
		"en-us": "VCS connection time out",
		"zh-cn": "VCS服务连接超时",
	},
	VcsNotExists: {
		"en-us": "repository does not exist",
		"zh-cn": "VCS仓库不存在",
	},
	VcsDeleteError: {
		"en-us": "VCS deletion failed",
		"zh-cn": "VCS存在相关依赖云模版，无法删除",
	},
	ImportError: {
		"en-us": "failed to import",
		"zh-cn": "导入出错",
	},
	ImportIdDuplicate: {
		"en-us": "import id was duplicated",
		"zh-cn": "id 重复",
	},
	ImportUpdateOrgId: {
		"en-us": "import failed",
		"zh-cn": "同 id 的数据己属于另一组织，无法使用“覆盖”方案(不允许更改组织 id)",
	},
	TaskApproveNotPending: {
		"en-us": "task is not awaiting for approve",
		"zh-cn": "作业状态非待审批，不允许操作",
	},
	KeyAlreadyExists: {
		"en-us": "key already exists",
		"zh-cn": "管理密钥已存在",
	},
	KeyNotExist: {
		"en-us": "key does not exist",
		"zh-cn": "管理密钥不存在",
	},
	KeyAliasDuplicate: {
		"en-us": "key alias exists",
		"zh-cn": "管理密钥名称重复",
	},
	KeyDecryptFail: {
		"en-us": "key decryption fail",
		"zh-cn": "管理密钥解析失败",
	},
	EnvCannotArchiveActive: {
		"en-us": " 无法归档",
		"zh-cn": "环境当前状态活跃",
	},
	InvalidTfVersion: {
		"en-us": "invalid terraform version",
		"zh-cn": "自动选择版本失败",
	},
	PolicyAlreadyExist: {
		"en-us": "policy already exist",
		"zh-cn": "策略已存在",
	},
	PolicyNotExist: {
		"en-us": "policy does not exist",
		"zh-cn": "策略不存在",
	},
	PolicyGroupAlreadyExist: {
		"en-us": "policy group already exist",
		"zh-cn": "策略组已存在",
	},
	PolicyGroupNotExist: {
		"en-us": "policy group does not exist",
		"zh-cn": "策略组不存在",
	},
	PolicyBelongedToAnotherGroup: {
		"en-us": "policy belonged to another group",
		"zh-cn": "策略属于其他策略组",
	},
	PolicyResultAlreadyExist: {
		"en-us": "policy result already exist",
		"zh-cn": "结果已存在",
	},
	PolicyResultNotExist: {
		"en-us": "policy result does not exist",
		"zh-cn": "结果不存在",
	},
	PolicyErrorParseTemplate: {
		"en-us": "template parse error",
		"zh-cn": "模板解析错误",
	},
	PolicyRegoMissingComment: {
		"en-us": "missing comment header in rego file",
		"zh-cn": "Rego脚本头缺失",
	},
	PolicySuppressNotExist: {
		"en-us": "suppress status does not exist",
		"zh-cn": "屏蔽记录不存在",
	},
	PolicySuppressAlreadyExist: {
		"en-us": "suppress status already exist",
		"zh-cn": "屏蔽记录已存在",
	},
	PolicyRelNotExist: {
		"en-us": "policy relation does not exist",
		"zh-cn": "策略关联关系不存在",
	},
	PolicyRelAlreadyExist: {
		"en-us": "policy relation already exist",
		"zh-cn": "策略关联关系已存在",
	},
	PolicyScanNotEnabled: {
		"en-us": "policy scan is not enabled",
		"zh-cn": "扫描未启用",
	},
	CronExpressError: {
		"en-us": "invalid cron expression",
		"zh-cn": "cron定时任务表达式错误",
	},
	CronTaskFailed: {
		"en-us": "cron task failed",
		"zh-cn": "cron定时任务执行失败",
	},
	PolicyMetaInvalid: {
		"en-us": "invalid meta json definition",
		"zh-cn": "策略元数据解析无效",
	},
	PolicyRegoInvalid: {
		"en-us": "invalid rego file",
		"zh-cn": "rego 脚本解析无效",
	},
	SystemConfigNotExist: {
		"en-us": "system config does not exist",
		"zh-cn": "当前配置不存在",
	},
	TemplateKeyIdNotSet: {
		"en-us": "ssh keypair is not setup",
		"zh-cn": "SSH 密钥未配置",
	},
	PolicyGroupDirError: {
		"en-us": "policy not found in the repository",
		"zh-cn": "仓库在当前目录找不到策略文件",
	},
}
